{
 "title": "Hero Demo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hero List Request Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri=\"/hero\"}"
    }
   ]
  },
  {
   "title": "Hero Feature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hero_usage_add_total[60s])",
     "legendFormat": "Add Hero Feature"
    },
    {
     "expr": "rate(hero_usage_search_total[60s])",
     "legendFormat": "Search Hero Feature"
    }
   ]
  },
  {
   "title": "Hero Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri=\"/hero\",status='200'}",
     "legendFormat": "Hero List"
    },
    {
     "expr": "http_server_requests_seconds_max{uri=\"/actuator/prometheus\", exception=\"None\"}",
     "legendFormat": "Metric"
    }
   ]
  },
  {
   "title": "Hero Request per Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/hero\", status=\"200\"}[5s])",
     "legendFormat": "Request to Hero List"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/hero/new\", method=\"GET\"}[5s])",
     "legendFormat": "Add new Hero"
    }
   ]
  },
  {
   "title": "Hero Repository All Hero Experiment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hero_repository_experiment_all_hero_runs_total{match = \"no\"}",
     "legendFormat": "Run Without Match"
    },
    {
     "expr": "hero_repository_experiment_all_hero_runs_total{match = \"yes\"}",
     "legendFormat": "Run With Match"
    },
    {
     "expr": "sum(hero_repository_experiment_all_hero_runs_total)",
     "legendFormat": "Total Run"
    }
   ]
  }
 ]
}